(require 'evil)
(require 'powerline)
(require 'airline-themes)
(require 'gruvbox-theme)
(require 'nix-mode)
(require 'haskell-mode)
(require 'scala-mode)
(require 'js2-mode)
(evil-mode 1)
(load-theme 'gruvbox-dark-soft t)
(load-theme 'airline-zenburn t)
